[package]
name = "keyoverlay-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.25"
poem = { version = "1.3.52", features = ["websocket", "static-files"] }
tokio = { version = "1.24.2", features = ["rt-multi-thread", "macros"] }

rdev = "0.5.2"
lazy_static = "1.4.0"

toml = "0.5.11"
serde = "1.0.152"
serde_json = "1.0.91"

msgbox = "0.7.0"
anyhow = "1.0.68"

egui = "0.20.1"
eframe = "0.20.1"
futures = "0.3.25"

open = "3.2.0"
tinyfiledialogs = "3.9.1"

[features]
debug = []
