[package]
name = "keyoverlay_daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6.2"
actix-web-actors = "4.1.0"
open = "3.0.3"

device_query = "1.1.1"

config = "0.13.1"
array_tool = "1.0.3"
serde = "1.0.145"

msgbox = "0.7.0"
tray-item = "0.7.1"

[build-dependencies]
windres = "*"